title: "Chance Young"
description: "Portfolio Project summaries with selective code."
url: "https://chanceyoung.dev"
baseurl: ""
created: 2025-09-11

markdown: kramdown
highlighter: rouge
permalink: /:title/   # pages get clean URLs

plugins:
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope: { path: "" }
    values: { layout: default }

collections:
  projects:
    output: true
    permalink: /projects/:name/
